FROM node:12

WORKDIR /usr/src/tmp

COPY . /usr/src/tmp/

RUN apt-get update

# 1. Get test packages
RUN rm -rf node_modules
RUN npm i

# Override the command, to run the test instead of the application
