import { REDIS_STORE_EXTENSIONS } from '../../../redisStores_Extensions';

const COMMON_REDIS_INFORMATION_STORES = ['analytics', 'emails', 'notifications', 'users'];
const REDIS_INFORMATION_STORES = [...COMMON_REDIS_INFORMATION_STORES, ...REDIS_STORE_EXTENSIONS];
const VOLATILE_DATA_STORES = ['emailVerificationCodes', 'magiclinks', 'sessions'];
const REDIS_STORES = [...REDIS_INFORMATION_STORES, ...VOLATILE_DATA_STORES];

export default { COMMON_REDIS_INFORMATION_STORES, REDIS_INFORMATION_STORES, REDIS_STORES, VOLATILE_DATA_STORES };
export { COMMON_REDIS_INFORMATION_STORES, REDIS_INFORMATION_STORES, REDIS_STORES, VOLATILE_DATA_STORES };
