name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2

    - name: deploy
      run: |
        echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
        chmod 400 ./identityFile.txt
      scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./build ubuntu@ec2-3-10-224-23.eu-west-2.compute.amazonaws.com:/home/ubuntu/:wqa

